//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.BizTalk.Framework.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GT.BizTalk.Framework.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is empty.
        /// </summary>
        internal static string ArgumentIsEmptyError {
            get {
                return ResourceManager.GetString("ArgumentIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{0}&apos; should be greater or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentNotGreaterOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentNotGreaterOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{0}&apos; should be lower or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentNotLowerOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentNotLowerOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Information Details:.
        /// </summary>
        internal static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Information Details:.
        /// </summary>
        internal static string ExceptionDetails1 {
            get {
                return ResourceManager.GetString("ExceptionDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER.
        /// </summary>
        internal static string ExceptionFormatterHeader {
            get {
                return ResourceManager.GetString("ExceptionFormatterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER.
        /// </summary>
        internal static string ExceptionFormatterHeader1 {
            get {
                return ResourceManager.GetString("ExceptionFormatterHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace Information Details:.
        /// </summary>
        internal static string ExceptionStackTraceDetails {
            get {
                return ResourceManager.GetString("ExceptionStackTraceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace Information Details:.
        /// </summary>
        internal static string ExceptionStackTraceDetails1 {
            get {
                return ResourceManager.GetString("ExceptionStackTraceDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Summary.
        /// </summary>
        internal static string ExceptionSummary {
            get {
                return ResourceManager.GetString("ExceptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Summary.
        /// </summary>
        internal static string ExceptionSummary1 {
            get {
                return ResourceManager.GetString("ExceptionSummary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument {0} cannot be initialised with its default value..
        /// </summary>
        internal static string ExceptionText_ArgumentCannotBeDefault {
            get {
                return ResourceManager.GetString("ExceptionText_ArgumentCannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument {0} cannot be initialised with its default value..
        /// </summary>
        internal static string ExceptionText_ArgumentCannotBeDefault1 {
            get {
                return ResourceManager.GetString("ExceptionText_ArgumentCannotBeDefault1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified boolean argument {0} must not be false..
        /// </summary>
        internal static string ExceptionText_BoolCannotBeFalse {
            get {
                return ResourceManager.GetString("ExceptionText_BoolCannotBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the argument {0} provided for the enumeration {1} is invalid..
        /// </summary>
        internal static string ExceptionText_InvalidEnumValue {
            get {
                return ResourceManager.GetString("ExceptionText_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the argument {0} provided for the enumeration {1} is invalid..
        /// </summary>
        internal static string ExceptionText_InvalidEnumValue1 {
            get {
                return ResourceManager.GetString("ExceptionText_InvalidEnumValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key {0} cannot be found in the dictionary..
        /// </summary>
        internal static string ExceptionText_MissingKeyInDictionary {
            get {
                return ResourceManager.GetString("ExceptionText_MissingKeyInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of parameters is too long. The maximum allowed number of parameters is {0}..
        /// </summary>
        internal static string ExceptionText_ParameterListTooLong {
            get {
                return ResourceManager.GetString("ExceptionText_ParameterListTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of parameters is too long. The maximum allowed number of parameters is {0}..
        /// </summary>
        internal static string ExceptionText_ParameterListTooLong1 {
            get {
                return ResourceManager.GetString("ExceptionText_ParameterListTooLong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string argument {0} must not be empty..
        /// </summary>
        internal static string ExceptionText_StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("ExceptionText_StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string argument {0} must not be empty..
        /// </summary>
        internal static string ExceptionText_StringCannotBeEmpty1 {
            get {
                return ResourceManager.GetString("ExceptionText_StringCannotBeEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type {0} is not compatible with {1}..
        /// </summary>
        internal static string ExceptionText_TypeNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionText_TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type {0} is not compatible with {1}..
        /// </summary>
        internal static string ExceptionText_TypeNotCompatible1 {
            get {
                return ResourceManager.GetString("ExceptionText_TypeNotCompatible1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string ExceptionType1 {
            get {
                return ResourceManager.GetString("ExceptionType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date time format is invalid..
        /// </summary>
        internal static string InvalidDateTimeFormatError {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize the payload: {0}.
        /// </summary>
        internal static string TextSerializationError {
            get {
                return ResourceManager.GetString("TextSerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid range for &apos;{0}&apos; is from 0 to 24.20:31:23.647.
        /// </summary>
        internal static string TimeSpanOutOfRangeError {
            get {
                return ResourceManager.GetString("TimeSpanOutOfRangeError", resourceCulture);
            }
        }
    }
}
