//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.BizTalk.Framework.Functoids.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GT.BizTalk.Framework.Functoids.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FMTDT_BITMAP {
            get {
                object obj = ResourceManager.GetObject("FMTDT_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats a string representing a DateTime value. The first parameter is the string representing a DateTime value to be formatted. If the functoid is used with 2 input parameters, the second parameter is the format of the output string. If the functoid is used with 3 parameters, the second parameter is the format of the input string and the third parameter is the format of the output string. If the functoid is used with 4 parameters, the fourth parameter is the default value to return if the parsing of the da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FMTDT_DESC {
            get {
                return ResourceManager.GetString("FMTDT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Date Time.
        /// </summary>
        internal static string FMTDT_NAME {
            get {
                return ResourceManager.GetString("FMTDT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats a date time string.
        /// </summary>
        internal static string FMTDT_TOOLTIP {
            get {
                return ResourceManager.GetString("FMTDT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GUIDGEN_BITMAP {
            get {
                object obj = ResourceManager.GetObject("GUIDGEN_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a new guid (as string)..
        /// </summary>
        internal static string GUIDGEN_DESC {
            get {
                return ResourceManager.GetString("GUIDGEN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid Generator.
        /// </summary>
        internal static string GUIDGEN_NAME {
            get {
                return ResourceManager.GetString("GUIDGEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a new guid (as string).
        /// </summary>
        internal static string GUIDGEN_TOOLTIP {
            get {
                return ResourceManager.GetString("GUIDGEN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OCA_BITMAP {
            get {
                object obj = ResourceManager.GetObject("OCA_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Orchestration Context Accessor functoid to access the context from an orchestration within a map. The first input parameter is the name of the message variable in the orchestration. The second parameter is the context property name. The third parameter is the context property namespace. The fourth parameter is optional and represents the value to be used if the context property is not found..
        /// </summary>
        internal static string OCA_DESC {
            get {
                return ResourceManager.GetString("OCA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestration Context Accessor.
        /// </summary>
        internal static string OCA_NAME {
            get {
                return ResourceManager.GetString("OCA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows access to the context from an orchestration within a map.
        /// </summary>
        internal static string OCA_TOOLTIP {
            get {
                return ResourceManager.GetString("OCA_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STRFORMAT_BITMAP {
            get {
                object obj = ResourceManager.GetObject("STRFORMAT_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the String Format functoid to format a text using the formatting string and arguments. This functoid accepts two to one hundred input parameters, the first parameter is the formatting string and at least one additional parameter with a value to be formatted..
        /// </summary>
        internal static string STRFORMAT_DESC {
            get {
                return ResourceManager.GetString("STRFORMAT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Format.
        /// </summary>
        internal static string STRFORMAT_NAME {
            get {
                return ResourceManager.GetString("STRFORMAT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format a text using the formatting string and arguments..
        /// </summary>
        internal static string STRFORMAT_TOOLTIP {
            get {
                return ResourceManager.GetString("STRFORMAT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STRPADLEFT_BITMAP {
            get {
                object obj = ResourceManager.GetObject("STRPADLEFT_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a new string that right-aligns the characters by padding them on the left with a specified character, for a specified total length..
        /// </summary>
        internal static string STRPADLEFT_DESC {
            get {
                return ResourceManager.GetString("STRPADLEFT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Pad Left.
        /// </summary>
        internal static string STRPADLEFT_NAME {
            get {
                return ResourceManager.GetString("STRPADLEFT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pads the string on the left with the specified character, for the specified total length..
        /// </summary>
        internal static string STRPADLEFT_TOOLTIP {
            get {
                return ResourceManager.GetString("STRPADLEFT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STRPADRIGHT_BITMAP {
            get {
                object obj = ResourceManager.GetObject("STRPADRIGHT_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a new string that left-aligns the characters by padding them on the right with a specified character, for a specified total length..
        /// </summary>
        internal static string STRPADRIGHT_DESC {
            get {
                return ResourceManager.GetString("STRPADRIGHT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Pad Right.
        /// </summary>
        internal static string STRPADRIGHT_NAME {
            get {
                return ResourceManager.GetString("STRPADRIGHT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pads the string on the right with the specified character, for the specified total length..
        /// </summary>
        internal static string STRPADRIGHT_TOOLTIP {
            get {
                return ResourceManager.GetString("STRPADRIGHT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STRTRIM_BITMAP {
            get {
                object obj = ResourceManager.GetObject("STRTRIM_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the String Trim functoid to remove leading and trailing spaces from a text item. This functoid requires one input parameter..
        /// </summary>
        internal static string STRTRIM_DESC {
            get {
                return ResourceManager.GetString("STRTRIM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Trim.
        /// </summary>
        internal static string STRTRIM_NAME {
            get {
                return ResourceManager.GetString("STRTRIM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes leading and trailing spaces from a text item..
        /// </summary>
        internal static string STRTRIM_TOOLTIP {
            get {
                return ResourceManager.GetString("STRTRIM_TOOLTIP", resourceCulture);
            }
        }
    }
}
